baseURL = "http://example.org/"
languageCode = "it"
title = "ADiC Umbria"
Paginate = 5
enableRobotsTXT = true
defaultContentLanguage = "it"

# `kissem` is the blog theme
# `juliette` is used to render pages over a static API
theme = [
    "kissem",
    "juliette",
]

[params.info]
poweredby = false
related = false
copyright = ""

[params.microblog]
number = 1

[outputs]
taxonomy = ["html", "json"]
